name: Lint README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for README file
        run: |
          if [ ! -f README.md ]; then
            echo "README.md не знайдено!" && exit 1
          else
            echo "Все ок: README.md знайдено."
